CREATE TABLE Zomato_Restaurants (
restaurant_id VARCHAR PRIMARY KEY,
restaurant_name VARCHAR,
city VARCHAR,
area VARCHAR,
cuisine VARCHAR,
avg_rating FLOAT,
total_ratings INT,
price_range VARCHAR,
delivery_available BOOLEAN
);

CREATE TABLE Zomato_Orders (
order_id VARCHAR PRIMARY KEY,
restaurant_id VARCHAR REFERENCES Zomato_Restaurants(restaurant_id),
customer_id VARCHAR,
order_date DATE,
order_time TIME,
delivery_time INT,
total_cost FLOAT,
item_count INT,
payment_method VARCHAR,
customer_rating FLOAT
);


----------------------------------------------------------------------------------------------------------

--Basic Data Cleaning:
--Remove duplicate records.
--Handle NULL values (if any) by replacing them with appropriate values.

DELETE FROM Zomato_Restaurants 
WHERE ctid NOT IN (
    SELECT MIN(ctid)
    FROM Zomato_Restaurants
    GROUP BY restaurant_name, city, area, cuisine
);

DELETE FROM Zomato_Orders
WHERE ctid NOT IN (
    SELECT MIN(ctid)
    FROM Zomato_Orders
    GROUP BY order_id, restaurant_id, customer_id, order_date,
             order_time, delivery_time, total_cost, item_count,
             payment_method, customer_rating
);

-----------------------------------------------------------------------------

UPDATE Zomato_Restaurants
SET restaurant_name = 'Unknown'
WHERE restaurant_name IS NULL;

UPDATE Zomato_Restaurants
SET city = 'Not Available'
WHERE city IS NULL;

UPDATE Zomato_Restaurants
SET area = 'Not Available'
WHERE area IS NULL;

UPDATE Zomato_Restaurants
SET cuisine = 'Others'
WHERE cuisine IS NULL;

UPDATE Zomato_Restaurants
SET avg_rating = (SELECT AVG(avg_rating) FROM Zomato_Restaurants)
WHERE avg_rating IS NULL;

UPDATE Zomato_Restaurants
SET total_ratings = 0
WHERE total_ratings IS NULL;

UPDATE Zomato_Restaurants
SET price_range = 'Medium'
WHERE price_range IS NULL;

UPDATE Zomato_Restaurants
SET delivery_available = 'No'
WHERE delivery_available IS NULL;

----------------------------------------------------------------------------------------

UPDATE Zomato_Orders
SET delivery_time = (SELECT AVG(delivery_time) FROM Zomato_Orders)
WHERE delivery_time IS NULL;

UPDATE Zomato_Orders
SET total_cost = 0
WHERE total_cost IS NULL;

UPDATE Zomato_Orders
SET item_count = 1
WHERE item_count IS NULL;

UPDATE Zomato_Orders
SET payment_method = 'Unknown'
WHERE payment_method IS NULL;

UPDATE Zomato_Orders
SET customer_rating = (SELECT AVG(customer_rating) FROM Zomato_Orders)
WHERE customer_rating IS NULL;

----------------------------------------------------------------------------------------------------

--2)Data Exploration Queries
--Count the number of restaurants in each city.
--Find the top 5 cities with the highest number of orders.
--Calculate the total revenue generated by each restaurant.

Select city, count(DISTINCT restaurant_name) from Zomato_restaurants
Group by city

select city, count(O.order_id) from Zomato_Orders O
Join Zomato_Restaurants R ON O.restaurant_id = R.restaurant_id
GROUP by city
Order by count(O.order_id) DESC
LIMIT 5

select restaurant_name, ROUND(SUM(O.total_cost)::numeric, 1) AS total_cost from Zomato_Orders O
Join Zomato_Restaurants R ON O.restaurant_id = R.restaurant_id
Group by restaurant_name
order by SUM(O.total_cost) DESC

-----------------------------------------------------------------------------------------------------------------------
--Data Aggregation
--Find the average order amount for each city.
--Identify the top 5 restaurants with the highest total sales.

select city, ROUND(AVG(O.total_cost)::numeric, 1) AS Average_cost from Zomato_Orders O
Join Zomato_Restaurants R ON O.restaurant_id = R.restaurant_id
Group by city
order by AVG(O.total_cost) DESC

select restaurant_name, ROUND(SUM(O.total_cost)::numeric, 1) AS total_cost from Zomato_Orders O
Join Zomato_Restaurants R ON O.restaurant_id = R.restaurant_id
GROUP by restaurant_name
Order by SUM(O.total_cost) DESC
LIMIT 5

-----------------------------------------------------------------------------------------------------------------------
--Data Joins
--Join the Zomato_Orders and Zomato_Restaurants tables to get restaurant names along with order details.

SELECT DISTINCT R.restaurant_name, O.* FROM Zomato_Orders O
JOIN Zomato_Restaurants R ON O.restaurant_id = R.restaurant_id
order by R.restaurant_name

----------------------------------------------------------------------------------------------------------------------------


